ARG DEBIAN_VERSION="12"

FROM debian:${DEBIAN_VERSION} as builder

ENV USER=nginx
ENV UID=101

RUN adduser \    
    --system \
    --disabled-password \    
    --gecos "" \    
    --home "/nonexistent" \    
    --shell "/sbin/nologin" \    
    --no-create-home \    
    --uid "${UID}" \
    "${USER}"

RUN apt update && apt -y install wget gnupg binutils && \
    wget "https://nginx.org/keys/nginx_signing.key" && \
    apt-key add nginx_signing.key && \
    echo "deb https://nginx.org/packages/mainline/debian/ bookworm nginx" >/etc/apt/sources.list.d/nginx.list && \
    apt update && \
    apt install -y nginx && \
    apt install -y busybox-static && \
    apt install --download-only --reinstall nginx lsb-base  libgcc-s1 libc6 libcrypt1 libpcre2-8-0 libssl3 zlib1g && \
    apt install --download-only --reinstall libidn2-0 debconf gcc-12-base && \
    for f in /var/cache/apt/archives/*.deb; do dpkg-deb -xv $f /packages; done && \
    rm -rf /packages/usr/share/bash-completion  \
        /packages/usr/share/debconf \
        /packages/usr/share/doc \
        /packages/usr/share/lintian	\
        /packages/usr/share/locale	\
        /packages/usr/share/man \
        /packages/usr/share/perl5  \
        /packages/usr/share/pixmaps \
        /packages/usr/share/docs \
        /packages/usr/bin \
        /packages/usr/sbin/dpkg* \
        /packages/usr/sbin/nginx-debug \
        /packages/var/cache/debconf \
        /packages/var/cache/apt/archives \
        /packages/etc/apt \
        /packages/etc/logrotate.d \
        /packages/etc/init.d \
        && \
    sed -i -E 's,listen(\s+)([0-9]+);,listen       8080;,' /packages/etc/nginx/conf.d/default.conf && \
    sed -i -E '/user(\s+)nginx;/d' /packages/etc/nginx/conf.d/default.conf && \
    busybox find /packages -xdev -print

RUN chown -R ${USER}: /var/cache /var/run

RUN touch /var/run/nginx.pid && \
    chown -R ${USER}: /var/run/nginx.pid

FROM gcr.io/distroless/static-debian${DEBIAN_VERSION}
COPY --from=builder /packages /
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group
COPY --from=builder /var/cache /var/cache
COPY --from=builder /var/run /var/run

RUN --mount=type=bind,from=builder,target=/mount ["/mount/bin/ln", "-sf", "/dev/stdout", "/var/log/nginx/access.log"]
RUN --mount=type=bind,from=builder,target=/mount ["/mount/bin/ln", "-sf", "/dev/stderr", "/var/log/nginx/error.log"]
RUN --mount=type=bind,from=builder,target=/mount ["/mount/bin/busybox", "rm", "-rfv", "/var/cache/apt", "/var/lib/dpkg", "/var/cache/debconf"]
RUN --mount=type=bind,from=builder,target=/mount ["/mount/bin/busybox", "find", "/", "-xdev", "-print"]

# Copy prepared nginx.conf to /etc/nginx

EXPOSE 8080

USER nginx

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
